#!/usr/bin/env bash

#
# Get path to the manuals directory.
SHELLNS_TMP_PATH_TO_DIR_MANUALS="$(tmpPath=$(dirname "${BASH_SOURCE[0]}"); realpath "${tmpPath}/src-manuals/${SHELLNS_CONFIG_INTERFACE_LOCALE}")"


#
# Mapp function to manual.
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_get"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/obj/get.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_new"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/obj/new.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_set"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/obj/set.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_any_array"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/any/array.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_any_comparable"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/any/comparable.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_any_date"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/any/date.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_any_datetime"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/any/datetime.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_any_number"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/any/number.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_any_time"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/any/time.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_array"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/array.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_assoc"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/assoc.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_bool"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/bool.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_char"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/char.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_charDecimal"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/charDecimal.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_charHex"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/charHex.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_charOctal"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/charOctal.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_code"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/code.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_color"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/color.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_date"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/date.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_dateTime"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/dateTime.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_dateTimeLocal"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/dateTimeLocal.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_dirExistentFullPath"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/dirExistentFullPath.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_dirExistentRelativePath"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/dirExistentRelativePath.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_dirFullPath"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/dirFullPath.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_dirName"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/dirName.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_dirNewFullPath"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/dirNewFullPath.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_dirNewRelativePath"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/dirNewRelativePath.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_dirRelativePath"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/dirRelativePath.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_fileExistentFullPath"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/fileExistentFullPath.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_fileExistentRelativePath"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/fileExistentRelativePath.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_fileFullPath"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/fileFullPath.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_fileName"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/fileName.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_fileNewFullPath"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/fileNewFullPath.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_fileNewRelativePath"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/fileNewRelativePath.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_fileRelativePath"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/fileRelativePath.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_fileSystemPath"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/filesystempath.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_float"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/float.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_function"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/function.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_hour"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/hour.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_int"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/int.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_minute"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/minute.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_mixed"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/mixed.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_month"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/month.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_regex"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/regex.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_string"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/string.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_type"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/type.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_check_utype"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/check/utype.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_convert_date_to_int"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/convert/date_to_int.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_convert_time_to_int"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/convert/time_to_int.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_types_values_split"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/types/values_split.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_utypes_to_array"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/utypes/to_array.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_validate_param"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/validate/param.man"
SHELLNS_MAPP_FUNCTION_TO_MANUAL["shellNS_validate_value"]="${SHELLNS_TMP_PATH_TO_DIR_MANUALS}/validate/value.man"


#
# Mapp namespace to function.
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["obj.get"]="shellNS_types_get"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["obj.new"]="shellNS_types_new"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["obj.set"]="shellNS_types_set"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.any.array"]="shellNS_types_check_any_array"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.any.comparable"]="shellNS_types_check_any_comparable"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.any.date"]="shellNS_types_check_any_date"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.any.datetime"]="shellNS_types_check_any_datetime"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.any.number"]="shellNS_types_check_any_number"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.any.time"]="shellNS_types_check_any_time"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.array"]="shellNS_types_check_array"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.assoc"]="shellNS_types_check_assoc"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.bool"]="shellNS_types_check_bool"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.char"]="shellNS_types_check_char"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.charDecimal"]="shellNS_types_check_charDecimal"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.charHex"]="shellNS_types_check_charHex"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.charOctal"]="shellNS_types_check_charOctal"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.code"]="shellNS_types_check_code"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.color"]="shellNS_types_check_color"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.date"]="shellNS_types_check_date"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.dateTime"]="shellNS_types_check_dateTime"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.dateTimeLocal"]="shellNS_types_check_dateTimeLocal"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.dirExistentFullPath"]="shellNS_types_check_dirExistentFullPath"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.dirExistentRelativePath"]="shellNS_types_check_dirExistentRelativePath"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.dirFullPath"]="shellNS_types_check_dirFullPath"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.dirName"]="shellNS_types_check_dirName"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.dirNewFullPath"]="shellNS_types_check_dirNewFullPath"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.dirNewRelativePath"]="shellNS_types_check_dirNewRelativePath"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.dirRelativePath"]="shellNS_types_check_dirRelativePath"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.fileExistentFullPath"]="shellNS_types_check_fileExistentFullPath"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.fileExistentRelativePath"]="shellNS_types_check_fileExistentRelativePath"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.fileFullPath"]="shellNS_types_check_fileFullPath"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.fileName"]="shellNS_types_check_fileName"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.fileNewFullPath"]="shellNS_types_check_fileNewFullPath"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.fileNewRelativePath"]="shellNS_types_check_fileNewRelativePath"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.fileRelativePath"]="shellNS_types_check_fileRelativePath"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.filesystempath"]="shellNS_types_check_fileSystemPath"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.float"]="shellNS_types_check_float"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.function"]="shellNS_types_check_function"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.hour"]="shellNS_types_check_hour"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.int"]="shellNS_types_check_int"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.minute"]="shellNS_types_check_minute"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.mixed"]="shellNS_types_check_mixed"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.month"]="shellNS_types_check_month"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.regex"]="shellNS_types_check_regex"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.string"]="shellNS_types_check_string"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.type"]="shellNS_types_check_type"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.check.utype"]="shellNS_types_check_utype"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.convert.date.to.int"]="shellNS_types_convert_date_to_int"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.convert.time.to.int"]="shellNS_types_convert_time_to_int"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["types.values.split"]="shellNS_types_values_split"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["utypes.to.array"]="shellNS_utypes_to_array"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["validate.param"]="shellNS_validate_param"
SHELLNS_MAPP_NAMESPACE_TO_FUNCTION["validate.value"]="shellNS_validate_value"





unset SHELLNS_TMP_PATH_TO_DIR_MANUALS